package com.appspot.ajnweb.tools;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: capability.proto

public final class Capability {

	private Capability() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
	}


	public static final class CapabilityConfig extends com.google.protobuf.GeneratedMessage {

		// Use CapabilityConfig.newBuilder() to construct.
		private CapabilityConfig() {
			initFields();
		}

		private CapabilityConfig(boolean noInit) {
		}


		private static final CapabilityConfig defaultInstance;


		public static CapabilityConfig getDefaultInstance() {
			return defaultInstance;
		}

		public CapabilityConfig getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return Capability.internal_static_CapabilityConfig_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return Capability.internal_static_CapabilityConfig_fieldAccessorTable;
		}


		public enum Status implements com.google.protobuf.ProtocolMessageEnum {
			ENABLED(0, 1), SCHEDULED(1, 2), DISABLED(2, 3), UNKNOWN(3, 4), ;

			public final int getNumber() {
				return value;
			}

			public static Status valueOf(int value) {
				switch (value) {
					case 1:
						return ENABLED;
					case 2:
						return SCHEDULED;
					case 3:
						return DISABLED;
					case 4:
						return UNKNOWN;
					default:
						return null;
				}
			}

			public static com.google.protobuf.Internal.EnumLiteMap<Status> internalGetValueMap() {
				return internalValueMap;
			}


			private static com.google.protobuf.Internal.EnumLiteMap<Status> internalValueMap =
					new com.google.protobuf.Internal.EnumLiteMap<Status>() {

						public Status findValueByNumber(int number) {
							return Status.valueOf(number);
						}
					};


			public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
				return getDescriptor().getValues().get(index);
			}

			public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
				return getDescriptor();
			}

			public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
				return Capability.CapabilityConfig.getDescriptor().getEnumTypes().get(0);
			}


			private static final Status[] VALUES = {
				ENABLED,
				SCHEDULED,
				DISABLED,
				UNKNOWN,
			};


			public static Status valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
				if (desc.getType() != getDescriptor()) {
					throw new java.lang.IllegalArgumentException(
							"EnumValueDescriptor is not for this type.");
				}
				return VALUES[desc.getIndex()];
			}


			private final int index;

			private final int value;


			private Status(int index, int value) {
				this.index = index;
				this.value = value;
			}


			static {
				Capability.getDescriptor();
			}

			// @@protoc_insertion_point(enum_scope:CapabilityConfig.Status)
		}


		// optional string package = 1;
		public static final int PACKAGE_FIELD_NUMBER = 1;

		private boolean hasPackage;

		private java.lang.String package_ = "";


		public boolean hasPackage() {
			return hasPackage;
		}

		public java.lang.String getPackage() {
			return package_;
		}


		// optional string capability = 2;
		public static final int CAPABILITY_FIELD_NUMBER = 2;

		private boolean hasCapability;

		private java.lang.String capability_ = "";


		public boolean hasCapability() {
			return hasCapability;
		}

		public java.lang.String getCapability() {
			return capability_;
		}


		// optional .CapabilityConfig.Status status = 3;
		public static final int STATUS_FIELD_NUMBER = 3;

		private boolean hasStatus;

		private Capability.CapabilityConfig.Status status_;


		public boolean hasStatus() {
			return hasStatus;
		}

		public Capability.CapabilityConfig.Status getStatus() {
			return status_;
		}


		// optional string internal_message = 4;
		public static final int INTERNAL_MESSAGE_FIELD_NUMBER = 4;

		private boolean hasInternalMessage;

		private java.lang.String internalMessage_ = "";


		public boolean hasInternalMessage() {
			return hasInternalMessage;
		}

		public java.lang.String getInternalMessage() {
			return internalMessage_;
		}


		// optional string admin_message = 5;
		public static final int ADMIN_MESSAGE_FIELD_NUMBER = 5;

		private boolean hasAdminMessage;

		private java.lang.String adminMessage_ = "";


		public boolean hasAdminMessage() {
			return hasAdminMessage;
		}

		public java.lang.String getAdminMessage() {
			return adminMessage_;
		}


		// optional string error_message = 6;
		public static final int ERROR_MESSAGE_FIELD_NUMBER = 6;

		private boolean hasErrorMessage;

		private java.lang.String errorMessage_ = "";


		public boolean hasErrorMessage() {
			return hasErrorMessage;
		}

		public java.lang.String getErrorMessage() {
			return errorMessage_;
		}


		// optional string scheduled_time = 7;
		public static final int SCHEDULED_TIME_FIELD_NUMBER = 7;

		private boolean hasScheduledTime;

		private java.lang.String scheduledTime_ = "";


		public boolean hasScheduledTime() {
			return hasScheduledTime;
		}

		public java.lang.String getScheduledTime() {
			return scheduledTime_;
		}

		private void initFields() {
			status_ = Capability.CapabilityConfig.Status.ENABLED;
		}

		public final boolean isInitialized() {
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (hasPackage()) {
				output.writeString(1, getPackage());
			}
			if (hasCapability()) {
				output.writeString(2, getCapability());
			}
			if (hasStatus()) {
				output.writeEnum(3, getStatus().getNumber());
			}
			if (hasInternalMessage()) {
				output.writeString(4, getInternalMessage());
			}
			if (hasAdminMessage()) {
				output.writeString(5, getAdminMessage());
			}
			if (hasErrorMessage()) {
				output.writeString(6, getErrorMessage());
			}
			if (hasScheduledTime()) {
				output.writeString(7, getScheduledTime());
			}
			getUnknownFields().writeTo(output);
		}


		private int memoizedSerializedSize = -1;


		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (hasPackage()) {
				size += com.google.protobuf.CodedOutputStream.computeStringSize(1, getPackage());
			}
			if (hasCapability()) {
				size += com.google.protobuf.CodedOutputStream.computeStringSize(2, getCapability());
			}
			if (hasStatus()) {
				size +=
						com.google.protobuf.CodedOutputStream.computeEnumSize(3, getStatus()
							.getNumber());
			}
			if (hasInternalMessage()) {
				size +=
						com.google.protobuf.CodedOutputStream.computeStringSize(4,
								getInternalMessage());
			}
			if (hasAdminMessage()) {
				size +=
						com.google.protobuf.CodedOutputStream.computeStringSize(5,
								getAdminMessage());
			}
			if (hasErrorMessage()) {
				size +=
						com.google.protobuf.CodedOutputStream.computeStringSize(6,
								getErrorMessage());
			}
			if (hasScheduledTime()) {
				size +=
						com.google.protobuf.CodedOutputStream.computeStringSize(7,
								getScheduledTime());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		public static Capability.CapabilityConfig parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static Capability.CapabilityConfig parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
		}

		public static Capability.CapabilityConfig parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static Capability.CapabilityConfig parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
		}

		public static Capability.CapabilityConfig parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static Capability.CapabilityConfig parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
		}

		public static Capability.CapabilityConfig parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static Capability.CapabilityConfig parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static Capability.CapabilityConfig parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static Capability.CapabilityConfig parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(Capability.CapabilityConfig prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}


		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> {

			private Capability.CapabilityConfig result;


			// Construct using Capability.CapabilityConfig.newBuilder()
			private Builder() {
			}

			private static Builder create() {
				Builder builder = new Builder();
				builder.result = new Capability.CapabilityConfig();
				return builder;
			}

			protected Capability.CapabilityConfig internalGetResult() {
				return result;
			}

			public Builder clear() {
				if (result == null) {
					throw new IllegalStateException("Cannot call clear() after build().");
				}
				result = new Capability.CapabilityConfig();
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(result);
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return Capability.CapabilityConfig.getDescriptor();
			}

			public Capability.CapabilityConfig getDefaultInstanceForType() {
				return Capability.CapabilityConfig.getDefaultInstance();
			}

			public boolean isInitialized() {
				return result.isInitialized();
			}

			public Capability.CapabilityConfig build() {
				if (result != null && !isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return buildPartial();
			}

			private Capability.CapabilityConfig buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				if (!isInitialized()) {
					throw newUninitializedMessageException(result)
						.asInvalidProtocolBufferException();
				}
				return buildPartial();
			}

			public Capability.CapabilityConfig buildPartial() {
				if (result == null) {
					throw new IllegalStateException(
							"build() has already been called on this Builder.");
				}
				Capability.CapabilityConfig returnMe = result;
				result = null;
				return returnMe;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Capability.CapabilityConfig) {
					return mergeFrom((Capability.CapabilityConfig) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Capability.CapabilityConfig other) {
				if (other == Capability.CapabilityConfig.getDefaultInstance())
					return this;
				if (other.hasPackage()) {
					setPackage(other.getPackage());
				}
				if (other.hasCapability()) {
					setCapability(other.getCapability());
				}
				if (other.hasStatus()) {
					setStatus(other.getStatus());
				}
				if (other.hasInternalMessage()) {
					setInternalMessage(other.getInternalMessage());
				}
				if (other.hasAdminMessage()) {
					setAdminMessage(other.getAdminMessage());
				}
				if (other.hasErrorMessage()) {
					setErrorMessage(other.getErrorMessage());
				}
				if (other.hasScheduledTime()) {
					setScheduledTime(other.getScheduledTime());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields =
						com.google.protobuf.UnknownFieldSet.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							this.setUnknownFields(unknownFields.build());
							return this;
						default: {
							if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
								this.setUnknownFields(unknownFields.build());
								return this;
							}
							break;
						}
						case 10: {
							setPackage(input.readString());
							break;
						}
						case 18: {
							setCapability(input.readString());
							break;
						}
						case 24: {
							int rawValue = input.readEnum();
							Capability.CapabilityConfig.Status value =
									Capability.CapabilityConfig.Status.valueOf(rawValue);
							if (value == null) {
								unknownFields.mergeVarintField(3, rawValue);
							} else {
								setStatus(value);
							}
							break;
						}
						case 34: {
							setInternalMessage(input.readString());
							break;
						}
						case 42: {
							setAdminMessage(input.readString());
							break;
						}
						case 50: {
							setErrorMessage(input.readString());
							break;
						}
						case 58: {
							setScheduledTime(input.readString());
							break;
						}
					}
				}
			}

			// optional string package = 1;
			public boolean hasPackage() {
				return result.hasPackage();
			}

			public java.lang.String getPackage() {
				return result.getPackage();
			}

			public Builder setPackage(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				result.hasPackage = true;
				result.package_ = value;
				return this;
			}

			public Builder clearPackage() {
				result.hasPackage = false;
				result.package_ = getDefaultInstance().getPackage();
				return this;
			}

			// optional string capability = 2;
			public boolean hasCapability() {
				return result.hasCapability();
			}

			public java.lang.String getCapability() {
				return result.getCapability();
			}

			public Builder setCapability(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				result.hasCapability = true;
				result.capability_ = value;
				return this;
			}

			public Builder clearCapability() {
				result.hasCapability = false;
				result.capability_ = getDefaultInstance().getCapability();
				return this;
			}

			// optional .CapabilityConfig.Status status = 3;
			public boolean hasStatus() {
				return result.hasStatus();
			}

			public Capability.CapabilityConfig.Status getStatus() {
				return result.getStatus();
			}

			public Builder setStatus(Capability.CapabilityConfig.Status value) {
				if (value == null) {
					throw new NullPointerException();
				}
				result.hasStatus = true;
				result.status_ = value;
				return this;
			}

			public Builder clearStatus() {
				result.hasStatus = false;
				result.status_ = Capability.CapabilityConfig.Status.ENABLED;
				return this;
			}

			// optional string internal_message = 4;
			public boolean hasInternalMessage() {
				return result.hasInternalMessage();
			}

			public java.lang.String getInternalMessage() {
				return result.getInternalMessage();
			}

			public Builder setInternalMessage(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				result.hasInternalMessage = true;
				result.internalMessage_ = value;
				return this;
			}

			public Builder clearInternalMessage() {
				result.hasInternalMessage = false;
				result.internalMessage_ = getDefaultInstance().getInternalMessage();
				return this;
			}

			// optional string admin_message = 5;
			public boolean hasAdminMessage() {
				return result.hasAdminMessage();
			}

			public java.lang.String getAdminMessage() {
				return result.getAdminMessage();
			}

			public Builder setAdminMessage(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				result.hasAdminMessage = true;
				result.adminMessage_ = value;
				return this;
			}

			public Builder clearAdminMessage() {
				result.hasAdminMessage = false;
				result.adminMessage_ = getDefaultInstance().getAdminMessage();
				return this;
			}

			// optional string error_message = 6;
			public boolean hasErrorMessage() {
				return result.hasErrorMessage();
			}

			public java.lang.String getErrorMessage() {
				return result.getErrorMessage();
			}

			public Builder setErrorMessage(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				result.hasErrorMessage = true;
				result.errorMessage_ = value;
				return this;
			}

			public Builder clearErrorMessage() {
				result.hasErrorMessage = false;
				result.errorMessage_ = getDefaultInstance().getErrorMessage();
				return this;
			}

			// optional string scheduled_time = 7;
			public boolean hasScheduledTime() {
				return result.hasScheduledTime();
			}

			public java.lang.String getScheduledTime() {
				return result.getScheduledTime();
			}

			public Builder setScheduledTime(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				result.hasScheduledTime = true;
				result.scheduledTime_ = value;
				return this;
			}

			public Builder clearScheduledTime() {
				result.hasScheduledTime = false;
				result.scheduledTime_ = getDefaultInstance().getScheduledTime();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:CapabilityConfig)
		}


		static {
			defaultInstance = new CapabilityConfig(true);
			Capability.internalForceInit();
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:CapabilityConfig)
	}

	public static final class CapabilityConfigList extends com.google.protobuf.GeneratedMessage {

		// Use CapabilityConfigList.newBuilder() to construct.
		private CapabilityConfigList() {
			initFields();
		}

		private CapabilityConfigList(boolean noInit) {
		}


		private static final CapabilityConfigList defaultInstance;


		public static CapabilityConfigList getDefaultInstance() {
			return defaultInstance;
		}

		public CapabilityConfigList getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return Capability.internal_static_CapabilityConfigList_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return Capability.internal_static_CapabilityConfigList_fieldAccessorTable;
		}


		// repeated .CapabilityConfig config = 1;
		public static final int CONFIG_FIELD_NUMBER = 1;

		private java.util.List<Capability.CapabilityConfig> config_ =
				java.util.Collections.emptyList();


		public java.util.List<Capability.CapabilityConfig> getConfigList() {
			return config_;
		}

		public int getConfigCount() {
			return config_.size();
		}

		public Capability.CapabilityConfig getConfig(int index) {
			return config_.get(index);
		}


		// optional .CapabilityConfigList default_config = 2;
		public static final int DEFAULT_CONFIG_FIELD_NUMBER = 2;

		private boolean hasDefaultConfig;

		private Capability.CapabilityConfigList defaultConfig_;


		public boolean hasDefaultConfig() {
			return hasDefaultConfig;
		}

		public Capability.CapabilityConfigList getDefaultConfig() {
			return defaultConfig_;
		}

		private void initFields() {
			defaultConfig_ = Capability.CapabilityConfigList.getDefaultInstance();
		}

		public final boolean isInitialized() {
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (Capability.CapabilityConfig element : getConfigList()) {
				output.writeMessage(1, element);
			}
			if (hasDefaultConfig()) {
				output.writeMessage(2, getDefaultConfig());
			}
			getUnknownFields().writeTo(output);
		}


		private int memoizedSerializedSize = -1;


		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			for (Capability.CapabilityConfig element : getConfigList()) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, element);
			}
			if (hasDefaultConfig()) {
				size +=
						com.google.protobuf.CodedOutputStream.computeMessageSize(2,
								getDefaultConfig());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		public static Capability.CapabilityConfigList parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static Capability.CapabilityConfigList parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
		}

		public static Capability.CapabilityConfigList parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static Capability.CapabilityConfigList parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
		}

		public static Capability.CapabilityConfigList parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static Capability.CapabilityConfigList parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
		}

		public static Capability.CapabilityConfigList parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static Capability.CapabilityConfigList parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static Capability.CapabilityConfigList parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static Capability.CapabilityConfigList parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(Capability.CapabilityConfigList prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}


		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> {

			private Capability.CapabilityConfigList result;


			// Construct using Capability.CapabilityConfigList.newBuilder()
			private Builder() {
			}

			private static Builder create() {
				Builder builder = new Builder();
				builder.result = new Capability.CapabilityConfigList();
				return builder;
			}

			protected Capability.CapabilityConfigList internalGetResult() {
				return result;
			}

			public Builder clear() {
				if (result == null) {
					throw new IllegalStateException("Cannot call clear() after build().");
				}
				result = new Capability.CapabilityConfigList();
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(result);
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return Capability.CapabilityConfigList.getDescriptor();
			}

			public Capability.CapabilityConfigList getDefaultInstanceForType() {
				return Capability.CapabilityConfigList.getDefaultInstance();
			}

			public boolean isInitialized() {
				return result.isInitialized();
			}

			public Capability.CapabilityConfigList build() {
				if (result != null && !isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return buildPartial();
			}

			private Capability.CapabilityConfigList buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				if (!isInitialized()) {
					throw newUninitializedMessageException(result)
						.asInvalidProtocolBufferException();
				}
				return buildPartial();
			}

			public Capability.CapabilityConfigList buildPartial() {
				if (result == null) {
					throw new IllegalStateException(
							"build() has already been called on this Builder.");
				}
				if (result.config_ != java.util.Collections.EMPTY_LIST) {
					result.config_ = java.util.Collections.unmodifiableList(result.config_);
				}
				Capability.CapabilityConfigList returnMe = result;
				result = null;
				return returnMe;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Capability.CapabilityConfigList) {
					return mergeFrom((Capability.CapabilityConfigList) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Capability.CapabilityConfigList other) {
				if (other == Capability.CapabilityConfigList.getDefaultInstance())
					return this;
				if (!other.config_.isEmpty()) {
					if (result.config_.isEmpty()) {
						result.config_ = new java.util.ArrayList<Capability.CapabilityConfig>();
					}
					result.config_.addAll(other.config_);
				}
				if (other.hasDefaultConfig()) {
					mergeDefaultConfig(other.getDefaultConfig());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields =
						com.google.protobuf.UnknownFieldSet.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							this.setUnknownFields(unknownFields.build());
							return this;
						default: {
							if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
								this.setUnknownFields(unknownFields.build());
								return this;
							}
							break;
						}
						case 10: {
							Capability.CapabilityConfig.Builder subBuilder =
									Capability.CapabilityConfig.newBuilder();
							input.readMessage(subBuilder, extensionRegistry);
							addConfig(subBuilder.buildPartial());
							break;
						}
						case 18: {
							Capability.CapabilityConfigList.Builder subBuilder =
									Capability.CapabilityConfigList.newBuilder();
							if (hasDefaultConfig()) {
								subBuilder.mergeFrom(getDefaultConfig());
							}
							input.readMessage(subBuilder, extensionRegistry);
							setDefaultConfig(subBuilder.buildPartial());
							break;
						}
					}
				}
			}

			// repeated .CapabilityConfig config = 1;
			public java.util.List<Capability.CapabilityConfig> getConfigList() {
				return java.util.Collections.unmodifiableList(result.config_);
			}

			public int getConfigCount() {
				return result.getConfigCount();
			}

			public Capability.CapabilityConfig getConfig(int index) {
				return result.getConfig(index);
			}

			public Builder setConfig(int index, Capability.CapabilityConfig value) {
				if (value == null) {
					throw new NullPointerException();
				}
				result.config_.set(index, value);
				return this;
			}

			public Builder setConfig(int index, Capability.CapabilityConfig.Builder builderForValue) {
				result.config_.set(index, builderForValue.build());
				return this;
			}

			public Builder addConfig(Capability.CapabilityConfig value) {
				if (value == null) {
					throw new NullPointerException();
				}
				if (result.config_.isEmpty()) {
					result.config_ = new java.util.ArrayList<Capability.CapabilityConfig>();
				}
				result.config_.add(value);
				return this;
			}

			public Builder addConfig(Capability.CapabilityConfig.Builder builderForValue) {
				if (result.config_.isEmpty()) {
					result.config_ = new java.util.ArrayList<Capability.CapabilityConfig>();
				}
				result.config_.add(builderForValue.build());
				return this;
			}

			public Builder addAllConfig(
					java.lang.Iterable<? extends Capability.CapabilityConfig> values) {
				if (result.config_.isEmpty()) {
					result.config_ = new java.util.ArrayList<Capability.CapabilityConfig>();
				}
				super.addAll(values, result.config_);
				return this;
			}

			public Builder clearConfig() {
				result.config_ = java.util.Collections.emptyList();
				return this;
			}

			// optional .CapabilityConfigList default_config = 2;
			public boolean hasDefaultConfig() {
				return result.hasDefaultConfig();
			}

			public Capability.CapabilityConfigList getDefaultConfig() {
				return result.getDefaultConfig();
			}

			public Builder setDefaultConfig(Capability.CapabilityConfigList value) {
				if (value == null) {
					throw new NullPointerException();
				}
				result.hasDefaultConfig = true;
				result.defaultConfig_ = value;
				return this;
			}

			public Builder setDefaultConfig(Capability.CapabilityConfigList.Builder builderForValue) {
				result.hasDefaultConfig = true;
				result.defaultConfig_ = builderForValue.build();
				return this;
			}

			public Builder mergeDefaultConfig(Capability.CapabilityConfigList value) {
				if (result.hasDefaultConfig()
						&& result.defaultConfig_ != Capability.CapabilityConfigList
							.getDefaultInstance()) {
					result.defaultConfig_ =
							Capability.CapabilityConfigList.newBuilder(result.defaultConfig_)
								.mergeFrom(value).buildPartial();
				} else {
					result.defaultConfig_ = value;
				}
				result.hasDefaultConfig = true;
				return this;
			}

			public Builder clearDefaultConfig() {
				result.hasDefaultConfig = false;
				result.defaultConfig_ = Capability.CapabilityConfigList.getDefaultInstance();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:CapabilityConfigList)
		}


		static {
			defaultInstance = new CapabilityConfigList(true);
			Capability.internalForceInit();
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:CapabilityConfigList)
	}

	public static final class IsEnabledRequest extends com.google.protobuf.GeneratedMessage {

		// Use IsEnabledRequest.newBuilder() to construct.
		private IsEnabledRequest() {
			initFields();
		}

		private IsEnabledRequest(boolean noInit) {
		}


		private static final IsEnabledRequest defaultInstance;


		public static IsEnabledRequest getDefaultInstance() {
			return defaultInstance;
		}

		public IsEnabledRequest getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return Capability.internal_static_IsEnabledRequest_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return Capability.internal_static_IsEnabledRequest_fieldAccessorTable;
		}


		// optional string pacakge = 1;
		public static final int PACAKGE_FIELD_NUMBER = 1;

		private boolean hasPacakge;

		private java.lang.String pacakge_ = "";


		public boolean hasPacakge() {
			return hasPacakge;
		}

		public java.lang.String getPacakge() {
			return pacakge_;
		}


		// repeated string capability = 2;
		public static final int CAPABILITY_FIELD_NUMBER = 2;

		private java.util.List<java.lang.String> capability_ = java.util.Collections.emptyList();


		public java.util.List<java.lang.String> getCapabilityList() {
			return capability_;
		}

		public int getCapabilityCount() {
			return capability_.size();
		}

		public java.lang.String getCapability(int index) {
			return capability_.get(index);
		}


		// repeated string call = 3;
		public static final int CALL_FIELD_NUMBER = 3;

		private java.util.List<java.lang.String> call_ = java.util.Collections.emptyList();


		public java.util.List<java.lang.String> getCallList() {
			return call_;
		}

		public int getCallCount() {
			return call_.size();
		}

		public java.lang.String getCall(int index) {
			return call_.get(index);
		}

		private void initFields() {
		}

		public final boolean isInitialized() {
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (hasPacakge()) {
				output.writeString(1, getPacakge());
			}
			for (java.lang.String element : getCapabilityList()) {
				output.writeString(2, element);
			}
			for (java.lang.String element : getCallList()) {
				output.writeString(3, element);
			}
			getUnknownFields().writeTo(output);
		}


		private int memoizedSerializedSize = -1;


		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (hasPacakge()) {
				size += com.google.protobuf.CodedOutputStream.computeStringSize(1, getPacakge());
			}
			{
				int dataSize = 0;
				for (java.lang.String element : getCapabilityList()) {
					dataSize +=
							com.google.protobuf.CodedOutputStream.computeStringSizeNoTag(element);
				}
				size += dataSize;
				size += 1 * getCapabilityList().size();
			}
			{
				int dataSize = 0;
				for (java.lang.String element : getCallList()) {
					dataSize +=
							com.google.protobuf.CodedOutputStream.computeStringSizeNoTag(element);
				}
				size += dataSize;
				size += 1 * getCallList().size();
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		public static Capability.IsEnabledRequest parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static Capability.IsEnabledRequest parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
		}

		public static Capability.IsEnabledRequest parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static Capability.IsEnabledRequest parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
		}

		public static Capability.IsEnabledRequest parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static Capability.IsEnabledRequest parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
		}

		public static Capability.IsEnabledRequest parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static Capability.IsEnabledRequest parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static Capability.IsEnabledRequest parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static Capability.IsEnabledRequest parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(Capability.IsEnabledRequest prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}


		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> {

			private Capability.IsEnabledRequest result;


			// Construct using Capability.IsEnabledRequest.newBuilder()
			private Builder() {
			}

			private static Builder create() {
				Builder builder = new Builder();
				builder.result = new Capability.IsEnabledRequest();
				return builder;
			}

			protected Capability.IsEnabledRequest internalGetResult() {
				return result;
			}

			public Builder clear() {
				if (result == null) {
					throw new IllegalStateException("Cannot call clear() after build().");
				}
				result = new Capability.IsEnabledRequest();
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(result);
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return Capability.IsEnabledRequest.getDescriptor();
			}

			public Capability.IsEnabledRequest getDefaultInstanceForType() {
				return Capability.IsEnabledRequest.getDefaultInstance();
			}

			public boolean isInitialized() {
				return result.isInitialized();
			}

			public Capability.IsEnabledRequest build() {
				if (result != null && !isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return buildPartial();
			}

			private Capability.IsEnabledRequest buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				if (!isInitialized()) {
					throw newUninitializedMessageException(result)
						.asInvalidProtocolBufferException();
				}
				return buildPartial();
			}

			public Capability.IsEnabledRequest buildPartial() {
				if (result == null) {
					throw new IllegalStateException(
							"build() has already been called on this Builder.");
				}
				if (result.capability_ != java.util.Collections.EMPTY_LIST) {
					result.capability_ = java.util.Collections.unmodifiableList(result.capability_);
				}
				if (result.call_ != java.util.Collections.EMPTY_LIST) {
					result.call_ = java.util.Collections.unmodifiableList(result.call_);
				}
				Capability.IsEnabledRequest returnMe = result;
				result = null;
				return returnMe;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Capability.IsEnabledRequest) {
					return mergeFrom((Capability.IsEnabledRequest) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Capability.IsEnabledRequest other) {
				if (other == Capability.IsEnabledRequest.getDefaultInstance())
					return this;
				if (other.hasPacakge()) {
					setPacakge(other.getPacakge());
				}
				if (!other.capability_.isEmpty()) {
					if (result.capability_.isEmpty()) {
						result.capability_ = new java.util.ArrayList<java.lang.String>();
					}
					result.capability_.addAll(other.capability_);
				}
				if (!other.call_.isEmpty()) {
					if (result.call_.isEmpty()) {
						result.call_ = new java.util.ArrayList<java.lang.String>();
					}
					result.call_.addAll(other.call_);
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields =
						com.google.protobuf.UnknownFieldSet.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							this.setUnknownFields(unknownFields.build());
							return this;
						default: {
							if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
								this.setUnknownFields(unknownFields.build());
								return this;
							}
							break;
						}
						case 10: {
							setPacakge(input.readString());
							break;
						}
						case 18: {
							addCapability(input.readString());
							break;
						}
						case 26: {
							addCall(input.readString());
							break;
						}
					}
				}
			}

			// optional string pacakge = 1;
			public boolean hasPacakge() {
				return result.hasPacakge();
			}

			public java.lang.String getPacakge() {
				return result.getPacakge();
			}

			public Builder setPacakge(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				result.hasPacakge = true;
				result.pacakge_ = value;
				return this;
			}

			public Builder clearPacakge() {
				result.hasPacakge = false;
				result.pacakge_ = getDefaultInstance().getPacakge();
				return this;
			}

			// repeated string capability = 2;
			public java.util.List<java.lang.String> getCapabilityList() {
				return java.util.Collections.unmodifiableList(result.capability_);
			}

			public int getCapabilityCount() {
				return result.getCapabilityCount();
			}

			public java.lang.String getCapability(int index) {
				return result.getCapability(index);
			}

			public Builder setCapability(int index, java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				result.capability_.set(index, value);
				return this;
			}

			public Builder addCapability(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				if (result.capability_.isEmpty()) {
					result.capability_ = new java.util.ArrayList<java.lang.String>();
				}
				result.capability_.add(value);
				return this;
			}

			public Builder addAllCapability(java.lang.Iterable<? extends java.lang.String> values) {
				if (result.capability_.isEmpty()) {
					result.capability_ = new java.util.ArrayList<java.lang.String>();
				}
				super.addAll(values, result.capability_);
				return this;
			}

			public Builder clearCapability() {
				result.capability_ = java.util.Collections.emptyList();
				return this;
			}

			// repeated string call = 3;
			public java.util.List<java.lang.String> getCallList() {
				return java.util.Collections.unmodifiableList(result.call_);
			}

			public int getCallCount() {
				return result.getCallCount();
			}

			public java.lang.String getCall(int index) {
				return result.getCall(index);
			}

			public Builder setCall(int index, java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				result.call_.set(index, value);
				return this;
			}

			public Builder addCall(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				if (result.call_.isEmpty()) {
					result.call_ = new java.util.ArrayList<java.lang.String>();
				}
				result.call_.add(value);
				return this;
			}

			public Builder addAllCall(java.lang.Iterable<? extends java.lang.String> values) {
				if (result.call_.isEmpty()) {
					result.call_ = new java.util.ArrayList<java.lang.String>();
				}
				super.addAll(values, result.call_);
				return this;
			}

			public Builder clearCall() {
				result.call_ = java.util.Collections.emptyList();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:IsEnabledRequest)
		}


		static {
			defaultInstance = new IsEnabledRequest(true);
			Capability.internalForceInit();
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:IsEnabledRequest)
	}

	public static final class IsEnabledResponse extends com.google.protobuf.GeneratedMessage {

		// Use IsEnabledResponse.newBuilder() to construct.
		private IsEnabledResponse() {
			initFields();
		}

		private IsEnabledResponse(boolean noInit) {
		}


		private static final IsEnabledResponse defaultInstance;


		public static IsEnabledResponse getDefaultInstance() {
			return defaultInstance;
		}

		public IsEnabledResponse getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return Capability.internal_static_IsEnabledResponse_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return Capability.internal_static_IsEnabledResponse_fieldAccessorTable;
		}


		public enum SummaryStatus implements com.google.protobuf.ProtocolMessageEnum {
			ENABLED(0, 1), SCHEDULED_FUTURE(1, 2), SCHEDULED_NOW(2, 3), DISABLED(3, 4), UNKNOWN(4,
					5), ;

			public final int getNumber() {
				return value;
			}

			public static SummaryStatus valueOf(int value) {
				switch (value) {
					case 1:
						return ENABLED;
					case 2:
						return SCHEDULED_FUTURE;
					case 3:
						return SCHEDULED_NOW;
					case 4:
						return DISABLED;
					case 5:
						return UNKNOWN;
					default:
						return null;
				}
			}

			public static com.google.protobuf.Internal.EnumLiteMap<SummaryStatus> internalGetValueMap() {
				return internalValueMap;
			}


			private static com.google.protobuf.Internal.EnumLiteMap<SummaryStatus> internalValueMap =
					new com.google.protobuf.Internal.EnumLiteMap<SummaryStatus>() {

						public SummaryStatus findValueByNumber(int number) {
							return SummaryStatus.valueOf(number);
						}
					};


			public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
				return getDescriptor().getValues().get(index);
			}

			public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
				return getDescriptor();
			}

			public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
				return Capability.IsEnabledResponse.getDescriptor().getEnumTypes().get(0);
			}


			private static final SummaryStatus[] VALUES = {
				ENABLED,
				SCHEDULED_FUTURE,
				SCHEDULED_NOW,
				DISABLED,
				UNKNOWN,
			};


			public static SummaryStatus valueOf(
					com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
				if (desc.getType() != getDescriptor()) {
					throw new java.lang.IllegalArgumentException(
							"EnumValueDescriptor is not for this type.");
				}
				return VALUES[desc.getIndex()];
			}


			private final int index;

			private final int value;


			private SummaryStatus(int index, int value) {
				this.index = index;
				this.value = value;
			}


			static {
				Capability.getDescriptor();
			}

			// @@protoc_insertion_point(enum_scope:IsEnabledResponse.SummaryStatus)
		}


		// optional .IsEnabledResponse.SummaryStatus summary_status = 1;
		public static final int SUMMARY_STATUS_FIELD_NUMBER = 1;

		private boolean hasSummaryStatus;

		private Capability.IsEnabledResponse.SummaryStatus summaryStatus_;


		public boolean hasSummaryStatus() {
			return hasSummaryStatus;
		}

		public Capability.IsEnabledResponse.SummaryStatus getSummaryStatus() {
			return summaryStatus_;
		}


		// optional int64 time_until_scheduled = 2;
		public static final int TIME_UNTIL_SCHEDULED_FIELD_NUMBER = 2;

		private boolean hasTimeUntilScheduled;

		private long timeUntilScheduled_ = 0L;


		public boolean hasTimeUntilScheduled() {
			return hasTimeUntilScheduled;
		}

		public long getTimeUntilScheduled() {
			return timeUntilScheduled_;
		}


		// repeated .CapabilityConfig config = 3;
		public static final int CONFIG_FIELD_NUMBER = 3;

		private java.util.List<Capability.CapabilityConfig> config_ =
				java.util.Collections.emptyList();


		public java.util.List<Capability.CapabilityConfig> getConfigList() {
			return config_;
		}

		public int getConfigCount() {
			return config_.size();
		}

		public Capability.CapabilityConfig getConfig(int index) {
			return config_.get(index);
		}

		private void initFields() {
			summaryStatus_ = Capability.IsEnabledResponse.SummaryStatus.ENABLED;
		}

		public final boolean isInitialized() {
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (hasSummaryStatus()) {
				output.writeEnum(1, getSummaryStatus().getNumber());
			}
			if (hasTimeUntilScheduled()) {
				output.writeInt64(2, getTimeUntilScheduled());
			}
			for (Capability.CapabilityConfig element : getConfigList()) {
				output.writeMessage(3, element);
			}
			getUnknownFields().writeTo(output);
		}


		private int memoizedSerializedSize = -1;


		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (hasSummaryStatus()) {
				size +=
						com.google.protobuf.CodedOutputStream.computeEnumSize(1, getSummaryStatus()
							.getNumber());
			}
			if (hasTimeUntilScheduled()) {
				size +=
						com.google.protobuf.CodedOutputStream.computeInt64Size(2,
								getTimeUntilScheduled());
			}
			for (Capability.CapabilityConfig element : getConfigList()) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, element);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		public static Capability.IsEnabledResponse parseFrom(com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static Capability.IsEnabledResponse parseFrom(com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
		}

		public static Capability.IsEnabledResponse parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static Capability.IsEnabledResponse parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
		}

		public static Capability.IsEnabledResponse parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static Capability.IsEnabledResponse parseFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
		}

		public static Capability.IsEnabledResponse parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static Capability.IsEnabledResponse parseDelimitedFrom(java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static Capability.IsEnabledResponse parseFrom(
				com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static Capability.IsEnabledResponse parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(Capability.IsEnabledResponse prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}


		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> {

			private Capability.IsEnabledResponse result;


			// Construct using Capability.IsEnabledResponse.newBuilder()
			private Builder() {
			}

			private static Builder create() {
				Builder builder = new Builder();
				builder.result = new Capability.IsEnabledResponse();
				return builder;
			}

			protected Capability.IsEnabledResponse internalGetResult() {
				return result;
			}

			public Builder clear() {
				if (result == null) {
					throw new IllegalStateException("Cannot call clear() after build().");
				}
				result = new Capability.IsEnabledResponse();
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(result);
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return Capability.IsEnabledResponse.getDescriptor();
			}

			public Capability.IsEnabledResponse getDefaultInstanceForType() {
				return Capability.IsEnabledResponse.getDefaultInstance();
			}

			public boolean isInitialized() {
				return result.isInitialized();
			}

			public Capability.IsEnabledResponse build() {
				if (result != null && !isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return buildPartial();
			}

			private Capability.IsEnabledResponse buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				if (!isInitialized()) {
					throw newUninitializedMessageException(result)
						.asInvalidProtocolBufferException();
				}
				return buildPartial();
			}

			public Capability.IsEnabledResponse buildPartial() {
				if (result == null) {
					throw new IllegalStateException(
							"build() has already been called on this Builder.");
				}
				if (result.config_ != java.util.Collections.EMPTY_LIST) {
					result.config_ = java.util.Collections.unmodifiableList(result.config_);
				}
				Capability.IsEnabledResponse returnMe = result;
				result = null;
				return returnMe;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Capability.IsEnabledResponse) {
					return mergeFrom((Capability.IsEnabledResponse) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Capability.IsEnabledResponse other) {
				if (other == Capability.IsEnabledResponse.getDefaultInstance())
					return this;
				if (other.hasSummaryStatus()) {
					setSummaryStatus(other.getSummaryStatus());
				}
				if (other.hasTimeUntilScheduled()) {
					setTimeUntilScheduled(other.getTimeUntilScheduled());
				}
				if (!other.config_.isEmpty()) {
					if (result.config_.isEmpty()) {
						result.config_ = new java.util.ArrayList<Capability.CapabilityConfig>();
					}
					result.config_.addAll(other.config_);
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields =
						com.google.protobuf.UnknownFieldSet.newBuilder(this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							this.setUnknownFields(unknownFields.build());
							return this;
						default: {
							if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
								this.setUnknownFields(unknownFields.build());
								return this;
							}
							break;
						}
						case 8: {
							int rawValue = input.readEnum();
							Capability.IsEnabledResponse.SummaryStatus value =
									Capability.IsEnabledResponse.SummaryStatus.valueOf(rawValue);
							if (value == null) {
								unknownFields.mergeVarintField(1, rawValue);
							} else {
								setSummaryStatus(value);
							}
							break;
						}
						case 16: {
							setTimeUntilScheduled(input.readInt64());
							break;
						}
						case 26: {
							Capability.CapabilityConfig.Builder subBuilder =
									Capability.CapabilityConfig.newBuilder();
							input.readMessage(subBuilder, extensionRegistry);
							addConfig(subBuilder.buildPartial());
							break;
						}
					}
				}
			}

			// optional .IsEnabledResponse.SummaryStatus summary_status = 1;
			public boolean hasSummaryStatus() {
				return result.hasSummaryStatus();
			}

			public Capability.IsEnabledResponse.SummaryStatus getSummaryStatus() {
				return result.getSummaryStatus();
			}

			public Builder setSummaryStatus(Capability.IsEnabledResponse.SummaryStatus value) {
				if (value == null) {
					throw new NullPointerException();
				}
				result.hasSummaryStatus = true;
				result.summaryStatus_ = value;
				return this;
			}

			public Builder clearSummaryStatus() {
				result.hasSummaryStatus = false;
				result.summaryStatus_ = Capability.IsEnabledResponse.SummaryStatus.ENABLED;
				return this;
			}

			// optional int64 time_until_scheduled = 2;
			public boolean hasTimeUntilScheduled() {
				return result.hasTimeUntilScheduled();
			}

			public long getTimeUntilScheduled() {
				return result.getTimeUntilScheduled();
			}

			public Builder setTimeUntilScheduled(long value) {
				result.hasTimeUntilScheduled = true;
				result.timeUntilScheduled_ = value;
				return this;
			}

			public Builder clearTimeUntilScheduled() {
				result.hasTimeUntilScheduled = false;
				result.timeUntilScheduled_ = 0L;
				return this;
			}

			// repeated .CapabilityConfig config = 3;
			public java.util.List<Capability.CapabilityConfig> getConfigList() {
				return java.util.Collections.unmodifiableList(result.config_);
			}

			public int getConfigCount() {
				return result.getConfigCount();
			}

			public Capability.CapabilityConfig getConfig(int index) {
				return result.getConfig(index);
			}

			public Builder setConfig(int index, Capability.CapabilityConfig value) {
				if (value == null) {
					throw new NullPointerException();
				}
				result.config_.set(index, value);
				return this;
			}

			public Builder setConfig(int index, Capability.CapabilityConfig.Builder builderForValue) {
				result.config_.set(index, builderForValue.build());
				return this;
			}

			public Builder addConfig(Capability.CapabilityConfig value) {
				if (value == null) {
					throw new NullPointerException();
				}
				if (result.config_.isEmpty()) {
					result.config_ = new java.util.ArrayList<Capability.CapabilityConfig>();
				}
				result.config_.add(value);
				return this;
			}

			public Builder addConfig(Capability.CapabilityConfig.Builder builderForValue) {
				if (result.config_.isEmpty()) {
					result.config_ = new java.util.ArrayList<Capability.CapabilityConfig>();
				}
				result.config_.add(builderForValue.build());
				return this;
			}

			public Builder addAllConfig(
					java.lang.Iterable<? extends Capability.CapabilityConfig> values) {
				if (result.config_.isEmpty()) {
					result.config_ = new java.util.ArrayList<Capability.CapabilityConfig>();
				}
				super.addAll(values, result.config_);
				return this;
			}

			public Builder clearConfig() {
				result.config_ = java.util.Collections.emptyList();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:IsEnabledResponse)
		}


		static {
			defaultInstance = new IsEnabledResponse(true);
			Capability.internalForceInit();
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:IsEnabledResponse)
	}


	private static com.google.protobuf.Descriptors.Descriptor internal_static_CapabilityConfig_descriptor;

	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_CapabilityConfig_fieldAccessorTable;

	private static com.google.protobuf.Descriptors.Descriptor internal_static_CapabilityConfigList_descriptor;

	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_CapabilityConfigList_fieldAccessorTable;

	private static com.google.protobuf.Descriptors.Descriptor internal_static_IsEnabledRequest_descriptor;

	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_IsEnabledRequest_fieldAccessorTable;

	private static com.google.protobuf.Descriptors.Descriptor internal_static_IsEnabledResponse_descriptor;

	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_IsEnabledResponse_fieldAccessorTable;


	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}


	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData =
				{
					"\n\020capability.proto\"\202\002\n\020CapabilityConfig\022"
							+ "\017\n\007package\030\001 \001(\t\022\022\n\ncapability\030\002 \001(\t\022(\n\006"
							+ "status\030\003 \001(\0162\030.CapabilityConfig.Status\022\030"
							+ "\n\020internal_message\030\004 \001(\t\022\025\n\radmin_messag"
							+ "e\030\005 \001(\t\022\025\n\rerror_message\030\006 \001(\t\022\026\n\016schedu"
							+ "led_time\030\007 \001(\t\"?\n\006Status\022\013\n\007ENABLED\020\001\022\r\n"
							+ "\tSCHEDULED\020\002\022\014\n\010DISABLED\020\003\022\013\n\007UNKNOWN\020\004\""
							+ "h\n\024CapabilityConfigList\022!\n\006config\030\001 \003(\0132"
							+ "\021.CapabilityConfig\022-\n\016default_config\030\002 \001"
							+ "(\0132\025.CapabilityConfigList\"E\n\020IsEnabledRe",
					"quest\022\017\n\007pacakge\030\001 \001(\t\022\022\n\ncapability\030\002 \003"
							+ "(\t\022\014\n\004call\030\003 \003(\t\"\360\001\n\021IsEnabledResponse\0228"
							+ "\n\016summary_status\030\001 \001(\0162 .IsEnabledRespon"
							+ "se.SummaryStatus\022\034\n\024time_until_scheduled"
							+ "\030\002 \001(\003\022!\n\006config\030\003 \003(\0132\021.CapabilityConfi"
							+ "g\"`\n\rSummaryStatus\022\013\n\007ENABLED\020\001\022\024\n\020SCHED"
							+ "ULED_FUTURE\020\002\022\021\n\rSCHEDULED_NOW\020\003\022\014\n\010DISA"
							+ "BLED\020\004\022\013\n\007UNKNOWN\020\005"
				};
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
				new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {

					public com.google.protobuf.ExtensionRegistry assignDescriptors(
							com.google.protobuf.Descriptors.FileDescriptor root) {
						descriptor = root;
						internal_static_CapabilityConfig_descriptor =
								getDescriptor().getMessageTypes().get(0);
						internal_static_CapabilityConfig_fieldAccessorTable =
								new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
										internal_static_CapabilityConfig_descriptor,
										new java.lang.String[] {
											"Package",
											"Capability",
											"Status",
											"InternalMessage",
											"AdminMessage",
											"ErrorMessage",
											"ScheduledTime",
										}, Capability.CapabilityConfig.class,
										Capability.CapabilityConfig.Builder.class);
						internal_static_CapabilityConfigList_descriptor =
								getDescriptor().getMessageTypes().get(1);
						internal_static_CapabilityConfigList_fieldAccessorTable =
								new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
										internal_static_CapabilityConfigList_descriptor,
										new java.lang.String[] {
											"Config",
											"DefaultConfig",
										}, Capability.CapabilityConfigList.class,
										Capability.CapabilityConfigList.Builder.class);
						internal_static_IsEnabledRequest_descriptor =
								getDescriptor().getMessageTypes().get(2);
						internal_static_IsEnabledRequest_fieldAccessorTable =
								new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
										internal_static_IsEnabledRequest_descriptor,
										new java.lang.String[] {
											"Pacakge",
											"Capability",
											"Call",
										}, Capability.IsEnabledRequest.class,
										Capability.IsEnabledRequest.Builder.class);
						internal_static_IsEnabledResponse_descriptor =
								getDescriptor().getMessageTypes().get(3);
						internal_static_IsEnabledResponse_fieldAccessorTable =
								new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
										internal_static_IsEnabledResponse_descriptor,
										new java.lang.String[] {
											"SummaryStatus",
											"TimeUntilScheduled",
											"Config",
										}, Capability.IsEnabledResponse.class,
										Capability.IsEnabledResponse.Builder.class);
						return null;
					}
				};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
				descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
	}


	public static void internalForceInit() {
	}

	// @@protoc_insertion_point(outer_class_scope)
}
